FROM ubuntu:18.04
ARG PACKAGE_VERSION
ARG APPLICATION_NAME
ENV PACKAGE_VERSION ${PACKAGE_VERSION}
ENV APPLICATION_NAME ${APPLICATION_NAME}
RUN dd if=/dev/zero of=fake_jar count=250 bs=1048576
EXPOSE 8880
CMD ["sh", "-c", "java -jar ${APPLICATION_NAME}-${PACKAGE_VERSION}.jar"]
